import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import CoffeeForm from '../components/Form/CoffeeForm'
import { Box } from '@mui/material'

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Buy Me A Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Buy Me A Coffee ☕️</h1>
        <Box
          sx={{
            marginTop: '20px',
            width: { lg: '30%', md: '50%', sm: '80%', xs: '100%' },
          }}
        >
          <CoffeeForm />
        </Box>
      </main>
    </div>
  )
}
